/****************************************************************************
****************** PrimeReact Demo Source (Auto-Generated) ******************
*****************************************************************************/

export const source = {
    "basic": "<Panel.Content>\n                            <p className=\"m-0\">\n                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\n                                commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim\n                                id est laborum.\n                            </p>\n                        </Panel.Content>",
    "preview": "<div>\n                    <Panel toggleable={false}>\n                        <Panel.Header>Header</Panel.Header>\n                        <Panel.Footer>Footer</Panel.Footer>\n                    </Panel>\n                </div>",
    "code": "import { Panel } from 'primereact/panel';\n\nexport default function BasicDemo() {\n    return (\n        <>\n            <div>\n                <div>\n                    <Panel toggleable={false}>\n                        <Panel.Header>Header</Panel.Header>\n                        <Panel.Content>\n                            <p className=\"m-0\">\n                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\n                                commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim\n                                id est laborum.\n                            </p>\n                        </Panel.Content>\n                        <Panel.Footer>Footer</Panel.Footer>\n                    </Panel>\n                </div>\n            </div>\n        </>\n    );\n}"
};
