export const SlideMenuDefaultProps = {
    __TYPE: 'SlideMenu',
    appendTo: null,
    autoZIndex: true,
    backLabel: 'Back',
    baseZIndex: 0,
    className: null,
    easing: 'ease-out',
    effectDuration: 250,
    id: null,
    menuWidth: 190,
    model: null,
    onHide: null,
    onShow: null,
    onNavigate: null,
    popup: false,
    style: null,
    transitionOptions: null,
    viewportHeight: 175
};
