import { ComponentBase } from '../componentbase/ComponentBase';

export const ListBoxBase = ComponentBase.extend({
    defaultProps: {
        __TYPE: 'ListBox',
        className: null,
        dataKey: null,
        disabled: null,
        emptyFilterMessage: null,
        emptyMessage: null,
        filter: false,
        filterIcon: null,
        filterBy: null,
        filterInputProps: null,
        filterLocale: undefined,
        filterMatchMode: 'contains',
        filterPlaceholder: null,
        filterTemplate: null,
        filterValue: null,
        id: null,
        itemTemplate: null,
        listClassName: null,
        listStyle: null,
        metaKeySelection: false,
        multiple: false,
        onChange: null,
        onFilterValueChange: null,
        optionDisabled: null,
        optionGroupChildren: null,
        optionGroupLabel: null,
        optionGroupTemplate: null,
        optionLabel: null,
        optionValue: null,
        options: null,
        style: null,
        tabIndex: 0,
        tooltip: null,
        tooltipOptions: null,
        value: null,
        virtualScrollerOptions: null,
        children: undefined
    }
});
