export { defaultContentProps } from './content';
export { defaultEllipsisProps } from './ellipsis';
export { defaultFirstProps } from './first';
export { defaultLastProps } from './last';
export { defaultNextProps } from './next';
export { defaultPageProps } from './page';
export { defaultPagesProps } from './pages';
export { defaultPrevProps } from './prev';
export { defaultRootProps } from './root';
