packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.6.1
    '@primeuix/utils': ^0.5.3
    '@primeuix/locale': ^0.0.1
    '@primeuix/styles': ^1.1.1
    '@primeuix/themes': ^1.1.1
    'tailwindcss-primeui': ^0.5.1
    'primeicons': ^7.0.0

catalogs:
    react19:
        '@types/react': ^19
        '@types/react-dom': ^19
        'react': ^19
        'react-dom': ^19
