packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@primeuix/styled': ^0.7.4
  '@primeuix/utils': ^0.6.2
  '@primeuix/locale': ^0.0.2
  '@primeuix/motion': ^0.0.10
  '@primeuix/styles': ^1
  '@primeuix/themes': ^1
  'tailwindcss-primeui': ^0.5.1
  'primeicons': ^7.0.0

catalogs:
  react19:
    '@types/react': ^19
    '@types/react-dom': ^19
    'react': ^19
    'react-dom': ^19
