export { defaultAcceptProps } from './accept';
export { defaultContentProps } from './content';
export { defaultFooterProps } from './footer';
export { defaultIconProps } from './icon';
export { defaultMessageProps } from './message';
export { defaultPortalProps } from './portal';
export { defaultRejectProps } from './reject';
export { defaultRootProps } from './root';
export { defaultTriggerProps } from './trigger';
