name: Bug report
description: Create a report to help us improve
title: "Component: Title"
labels: "defect,:bangbang: needs-triage"
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: >
        ### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours
      # yamllint enable rule:line-length
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: reproducer
    attributes:
      label: Reproducer
      placeholder: https://codesandbox.io/s/primereact-test-forked-bbns8k
      description: |
        Please fork the [CodeSandbox project](https://codesandbox.io/s/primereact-test-forked-bbns8k) and create a case demonstrating your bug report. Issues **without** a CodeSandbox have much less possibility to be reviewed.
    validations:
      required: false
  - type: input
    id: pr-version
    attributes:
      label: PrimeReact version
      placeholder: x.x.x
    validations:
      required: true
  - type: dropdown
    id: react-version
    attributes:
      label: React version
      multiple: false
      options:
        - 17.x
        - 18.x
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language
      multiple: false
      options:
        - TypeScript
        - ES5
        - ES6
        - ALL
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: Build / Runtime
      multiple: false
      options:
        - Create React App (CRA)
        - Next.js
        - Remix
        - Vite
        - Hydrogen
        - Relay
        - Preact
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: Browser(s)
      description: List specific browser(s) the problem occurs on or leave blank if ALL browsers
      placeholder: >
        e.g. Safari 15, iOS 15.4, Chrome 90
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise description of how to make the issue happen.
      placeholder: >
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
