import { ComponentBase } from '../componentbase/ComponentBase';

export const GalleriaBase = ComponentBase.extend({
    defaultProps: {
        __TYPE: 'Galleria',
        id: null,
        value: null,
        activeIndex: 0,
        fullScreen: false,
        item: null,
        thumbnail: null,
        indicator: null,
        caption: null,
        className: null,
        closeIcon: null,
        style: null,
        header: null,
        footer: null,
        numVisible: 3,
        responsiveOptions: null,
        showItemNavigators: false,
        showThumbnailNavigators: true,
        showItemNavigatorsOnHover: false,
        changeItemOnIndicatorHover: false,
        circular: false,
        autoPlay: false,
        transitionInterval: 4000,
        showThumbnails: true,
        itemNextIcon: null,
        itemPrevIcon: null,
        nextThumbnailIcon: null,
        prevThumbnailIcon: null,
        thumbnailsPosition: 'bottom',
        verticalThumbnailViewPortHeight: '300px',
        showIndicators: false,
        showIndicatorsOnItem: false,
        indicatorsPosition: 'bottom',
        baseZIndex: 0,
        transitionOptions: null,
        onItemChange: null,
        children: undefined
    }
});
