import { ObjectUtils } from '../utils/Utils';

export const TreeSelectBase = {
    defaultProps: {
        __TYPE: 'TreeSelect',
        appendTo: null,
        ariaLabel: null,
        ariaLabelledBy: null,
        className: null,
        disabled: false,
        display: 'comma',
        dropdownIcon: 'pi pi-chevron-down',
        emptyMessage: null,
        expandedKeys: null,
        filter: false,
        filterBy: 'label',
        filterInputAutoFocus: true,
        filterLocale: undefined,
        filterMode: 'lenient',
        filterPlaceholder: null,
        filterTemplate: null,
        filterValue: null,
        inputId: null,
        inputRef: null,
        metaKeySelection: true,
        name: null,
        onChange: null,
        onFilterValueChange: null,
        onHide: null,
        onNodeCollapse: null,
        onNodeExpand: null,
        onNodeSelect: null,
        onNodeUnselect: null,
        onShow: null,
        options: null,
        panelClassName: null,
        panelFooterTemplate: null,
        panelHeaderTemplate: null,
        panelStyle: null,
        placeholder: null,
        resetFilterOnHide: false,
        scrollHeight: '400px',
        selectionMode: 'single',
        style: null,
        tabIndex: null,
        transitionOptions: null,
        value: null,
        valueTemplate: null,
        children: undefined
    },
    getProps: (props) => ObjectUtils.getMergedProps(props, TreeSelectBase.defaultProps),
    getOtherProps: (props) => ObjectUtils.getDiffProps(props, TreeSelectBase.defaultProps)
};
