import { ComponentBase } from '../componentbase/ComponentBase';

export const TreeSelectBase = ComponentBase.extend({
    defaultProps: {
        __TYPE: 'TreeSelect',
        appendTo: null,
        ariaLabel: null,
        ariaLabelledBy: null,
        className: null,
        closeIcon: null,
        disabled: false,
        display: 'comma',
        dropdownIcon: null,
        emptyMessage: null,
        expandedKeys: null,
        filter: false,
        filterBy: 'label',
        filterIcon: null,
        filterInputAutoFocus: true,
        filterLocale: undefined,
        filterMode: 'lenient',
        filterPlaceholder: null,
        filterTemplate: null,
        filterValue: null,
        inputId: null,
        inputRef: null,
        metaKeySelection: true,
        name: null,
        nodeTemplate: null,
        onChange: null,
        onFilterValueChange: null,
        onHide: null,
        onNodeCollapse: null,
        onNodeExpand: null,
        onNodeSelect: null,
        onNodeUnselect: null,
        onShow: null,
        options: null,
        panelClassName: null,
        panelFooterTemplate: null,
        panelHeaderTemplate: null,
        panelStyle: null,
        placeholder: null,
        resetFilterOnHide: false,
        scrollHeight: '400px',
        selectionMode: 'single',
        style: null,
        tabIndex: null,
        togglerTemplate: null,
        transitionOptions: null,
        value: null,
        valueTemplate: null,
        children: undefined
    }
});
