import type { useDatePickerProps } from '@primereact/types/shared/datepicker';

export const defaultProps: useDatePickerProps = {
    defaultValue: undefined,
    value: undefined,
    updateModelType: 'date',
    selectionMode: 'single',
    dateFormat: undefined,
    inline: false,
    selectOtherMonths: false,
    numberOfMonths: 1,
    view: 'date',
    minDate: undefined,
    maxDate: undefined,
    maxDateCount: undefined,
    showOnFocus: true,
    autoZIndex: true,
    baseZIndex: 0,
    shortYearCutoff: '+10',
    showTime: false,
    timeOnly: false,
    hourFormat: '24',
    stepHour: 1,
    stepMinute: 1,
    stepSecond: 1,
    hideOnDateTimeSelect: false,
    hideOnRangeSelection: false,
    timeSeparator: ':',
    manualInput: true,
    showSeconds: false,
    appendTo: 'body',
    onValueChange: undefined,
    onDateSelect: undefined,
    onMonthChange: undefined,
    onYearChange: undefined,
    onTodayButtonClick: undefined,
    onClearButtonClick: undefined,
    onInput: undefined,
    onKeyDown: undefined,
    onFocus: undefined,
    onBlur: undefined
};
