export * as DatePicker from './UIDatePicker.parts';

// Named runtime exports to maximize tree-shaking
export {
    DatePickerAmPm,
    DatePickerButtonbar,
    DatePickerCalendar,
    DatePickerClear,
    DatePickerClearIcon,
    DatePickerContainer,
    DatePickerDecade,
    DatePickerDropdown,
    DatePickerDropdownIcon,
    DatePickerFooter,
    DatePickerHeader,
    DatePickerHour,
    DatePickerInputIconContainer,
    DatePickerMinute,
    DatePickerPanel,
    DatePickerPicker,
    DatePickerPortal,
    DatePickerProps,
    DatePickerProvider,
    DatePickerSecond,
    DatePickerSelectMonth,
    DatePickerSelectYear,
    DatePickerSeparator,
    DatePickerSeparatorContainer,
    DatePickerTable,
    DatePickerTableBody,
    DatePickerTableBodyCell,
    DatePickerTableBodyRow,
    DatePickerTableBodyWeekCell,
    DatePickerTableHead,
    DatePickerTableHeadCell,
    DatePickerTableHeadRow,
    DatePickerTableHeadWeekCell,
    DatePickerTime,
    DatePickerTitle,
    defaultAmPmProps,
    defaultButtonbarProps,
    defaultCalendarProps,
    defaultClearIconProps,
    defaultClearProps,
    defaultContainerProps,
    defaultDecadeProps,
    defaultDecrementProps,
    defaultDropdownIconProps,
    defaultDropdownProps,
    defaultFooterProps,
    defaultHeaderProps,
    defaultHourProps,
    defaultIncrementProps,
    defaultInputIconContainerProps,
    defaultInputProps,
    defaultMinuteProps,
    defaultNextProps,
    defaultPanelProps,
    defaultPickerProps,
    defaultPortalProps,
    defaultPrevProps,
    defaultRootProps,
    defaultSecondProps,
    defaultSelectMonthProps,
    defaultSelectYearProps,
    defaultSeparatorContainerProps,
    defaultSeparatorProps,
    defaultTableBodyCellProps,
    defaultTableBodyProps,
    defaultTableBodyRowProps,
    defaultTableBodyWeekCellProps,
    defaultTableHeadCellProps,
    defaultTableHeadProps,
    defaultTableHeadRowProps,
    defaultTableHeadWeekCellProps,
    defaultTableProps,
    defaultTimeProps,
    defaultTitleProps,
    defaultTodayProps,
    useDatePickerContext
} from 'primereact/datepicker';
export { UIDatePickerDecrement as DatePickerDecrement } from './decrement';
export { UIDatePickerIncrement as DatePickerIncrement } from './increment';
export { UIDatePickerInput as DatePickerInput } from './input';
export { UIDatePickerNext as DatePickerNext } from './next';
export { UIDatePickerPrev as DatePickerPrev } from './prev';
export { UIDatePickerRoot as DatePickerRoot } from './root';
export { UIDatePickerToday as DatePickerToday } from './today';
