name: Generate API DOC

on:
  push:
    branches: [ master ]
    paths:
      - '**/**/*.d.ts'
      - 'api-generator/build-apidoc.js'

permissions:
  contents: write

jobs:
  build:
    if: github.repository == 'primefaces/primereact' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install node packages
      run: npm install

    - name: Generate api doc
      run: npm run apidoc

    - name: Commit doc
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git commit -a -m "Update API doc"
        git push
