name: Issue Inactive Checker

on:
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:
  
permissions:
  contents: read
  
jobs:
  issue-close-require:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Cannot Replicate
        uses: actions/stale@v11
        with:
          days-before-stale: 20
          days-before-close: 0
          only-labels: "Resolution: Cannot Replicate"
          stale-issue-label: "Resolution: Cannot Replicate"
          close-issue-message: >
            This issue has been automatically closed due to inactivity for 20 days.
            If this is still relevant, please open a new issue with a reproducer.
          days-before-pr-stale: -1
          days-before-pr-close: -1

      - name: Needs Reproducer
        uses: actions/stale@v11
        with:
          days-before-stale: 20
          days-before-close: 0
          only-labels: "Status: Needs Reproducer"
          stale-issue-label: "Status: Needs Reproducer"
          close-issue-message: >
            This issue has been automatically closed due to inactivity for 20 days.
            If this is still relevant, please open a new issue with a reproducer.
          days-before-pr-stale: -1
          days-before-pr-close: -1

      - name: Duplicate
        uses: actions/stale@v11
        with:
          days-before-stale: 20
          days-before-close: 0
          only-labels: "Resolution: Duplicate"
          stale-issue-label: "Resolution: Duplicate"
          close-issue-message: >
            This issue has been automatically closed due to inactivity for 20 days.
            If this is still relevant, please open a new issue with a reproducer.
          days-before-pr-stale: -1
          days-before-pr-close: -1
